Repository atomic-router/atomic-router, pull requests merged in 2022-08, with the labels that each got.

#22 Move release process into contributing.md
  CONTRIBUTING.md
  README.md
Labels: documentation

#24 Fix steps names in `publish` ci
  .github/workflows/publish.yml
Labels: chore

#25 Fix SSR support regression
  babel-preset.js
  babel.config.js
  build/minifications.js
  package.json
  rollup.config.js
  yarn.lock
Labels: fix

#26 Update README.md
  README.md
Labels: documentation
