Repository atomic-router/atomic-router, pull requests merged in 2022-09, with the labels that each got.

#37 remove async handlers to improve performance
  src/create-history-router.ts
  src/create-route.ts
  test/chain-route.test.ts
  test/create-history-router.test.ts
  test/redirect.test.ts
Labels: enhancement

#36 add `serialize` parameter to `createHistoryRouter`
  package.json
  src/create-history-router.ts
  src/types.ts
  src/utils/build-path.ts
  test/create-history-router.test.ts
  yarn.lock
Labels: feature

#38 Migrate tests to vitest
  jest.config.js
  package.json
  test/chain-route.test.ts
  test/create-history-router.test.ts
  test/create-route.test.ts
  test/match-path.test.ts
  test/not-found-route.test.ts
  test/redirect.test.ts
  vitest.config.ts
  yarn.lock
Labels: tests

#42 `querySync` operator
  src/index.ts
  src/methods/query-sync.ts
  test/query-sync.test.ts
Labels: feature
